---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: asdasd
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/sympatheticmoose/podinfo-deploy.git

